# Generated by Django 2.2.1 on 2019-06-05 01:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PencilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_description', models.CharField(max_length=300)),
                ('type_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PencilManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_description', models.CharField(max_length=300)),
                ('manufacturer_for_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Pages.PencilType', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Pencil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pencil_name', models.CharField(max_length=200)),
                ('pencil_description', models.TextField()),
                ('pencil_last_updated', models.DateTimeField(default=datetime.datetime(2019, 6, 5, 1, 1, 14, 118108, tzinfo=utc))),
                ('pencil_published_date', models.DateTimeField(blank=True, null=True)),
                ('pencil_slug', models.CharField(default=1, max_length=200)),
                ('pencil_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pencil_for_manufacturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Pages.PencilManufacturer', verbose_name='Pencil')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('comment_published_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 5, 1, 1, 14, 119108, tzinfo=utc))),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.Pencil')),
            ],
        ),
    ]
