# Generated by Django 2.2.1 on 2019-06-05 01:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pencil',
            name='pencil_already_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 5, 1, 51, 38, 659256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pencil',
            name='pencil_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
