# Generated by Django 2.2.1 on 2019-06-10 01:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_auto_20190604_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 1, 14, 9, 173076, tzinfo=utc)),
        ),
    ]
