# Generated by Django 2.2.1 on 2019-06-10 02:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20190609_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pencil',
            name='pencil_already_published',
        ),
        migrations.RemoveField(
            model_name='pencil',
            name='pencil_last_updated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 2, 16, 12, 828183, tzinfo=utc)),
        ),
    ]
