# Generated by Django 2.2.1 on 2019-06-10 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_auto_20190609_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 2, 43, 54, 586667, tzinfo=utc)),
        ),
    ]
