# Generated by Django 2.2.1 on 2019-06-10 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_auto_20190609_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 2, 54, 57, 693122, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='pencil',
            unique_together={('pencil_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='pencilmanufacturer',
            unique_together={('manufacturer_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='penciltype',
            unique_together={('type_slug',)},
        ),
    ]
