# Generated by Django 2.2.1 on 2019-06-10 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_auto_20190609_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 2, 56, 54, 504649, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='pencil',
            unique_together={('pencil_slug', 'pencil_name')},
        ),
    ]
