# Generated by Django 2.2.1 on 2019-06-10 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_auto_20190609_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pencil',
            name='pencil_brief_description',
            field=models.CharField(default=models.CharField(max_length=200), max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 17, 53, 55, 388506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pencil',
            name='pencil_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 10, 17, 53, 55, 387507, tzinfo=utc)),
        ),
    ]
