# Generated by Django 2.2.2 on 2019-06-14 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_auto_20190610_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 3, 57, 35, 547202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pencil',
            name='pencil_published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 14, 3, 57, 35, 547202, tzinfo=utc)),
        ),
    ]
